apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mychart.fullname" . }}-env
  labels:
    {{- include "mychart.labels" . | nindent 4 }}
data:
  DEBUGMODE: {{ .Values.debugMode | quote }}
  NAMESPACE: {{ .Release.Namespace | quote }}
  POD_NAME: {{ include "mychart.fullname" . }}-{{ .Values.replicaCount }}
